apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-contianer
        image: mysql:8
        ports:
          - containerPort: 3306
            protocol: TCP
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootroot
          - name: MYSQL_DATABASE
            value: students-db
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: admin
         
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: appport
      port: 3306
      protocol: TCP
      targetPort: 3306
